### ISSUE TITLE
How do you reference this?

### ISSUE THREAD

**Issue by laura-burns** [cloudfoundry/java-buildpack-security-provider#2]
Hey not sure if this project is in a stable state, but I am using PCF and PAS and want to check for the updated certificates and keys to our java microservices.  I can't find any documentation on how to do it, but seems this library may do what is required.  How do I get the new certificate created from this library?

**Comment by nebhale** [comment]
A better description of this project's behavior can be found [in the buildpack](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-container_security_provider.md#security-provider).  It is added automatically to all Java applications staged with the buildpack and behaves as described there, for the default `SSLContext`.

**Comment by laura-burns** [comment]
Is there a java example of how to access the certificate from the TrustManager and KeyManager so that I can pass my service's certificate to another microservice? 

ie  is this correct?

@Bean
    public RestTemplate restTemplate() throws Exception {
        System.out.println("In custom restTemplate");
        KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
        keyStore.load(null);

        TrustManagerFactory tmfactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        tmfactory.init(keyStore);
        KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        kmf.init(keyStore, "1234".toCharArray()); //todo: this should change

        System.out.println("Getting TrustStore");
        tmfactory.getTrustManagers();
        
        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(kmf.getKeyManagers(), tmfactory.getTrustManagers(), null);

        SSLConnectionSocketFactory socketFactory = new SSLConnectionSocketFactory(sslContext);
        HttpClient httpClient = HttpClients.custom()
                .setSSLSocketFactory(socketFactory)
                .build();
        HttpComponentsClientHttpRequestFactory factory2 = new HttpComponentsClientHttpRequestFactory(httpClient);

        return new RestTemplate(factory2);
}

**Comment by nebhale** [comment]
The traditional way this is handled is by using the default `SSLContext` which nearly all libraries already do by default.  So if you create a `new RestTemplate()`, it will automatically do the right thing.  For example the following code:

```java
@RestController
@SpringBootApplication
public class TrustDemoApplication {

    private final Logger logger = LoggerFactory.getLogger(this.getClass());

    public static void main(String[] args) {
        SpringApplication.run(TrustDemoApplication.class, args);
    }

    @GetMapping("/")
    void home() {
        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<String> result = restTemplate.getForEntity("https://google.com", String.class);
        this.logger.info("{}", result);
    }

}
```

returns the following output in a CF environment (timestamps elided for clarity):

```
JVM Memory Configuration: -Xmx451151K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=85424K
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.2.RELEASE)
INFO 8 --- [           main] pertySourceApplicationContextInitializer : 'cloud' property source added
INFO 8 --- [           main] nfigurationApplicationContextInitializer : Reconfiguration enabled
INFO 8 --- [           main] i.p.trustdemo.TrustDemoApplication       : Starting TrustDemoApplication on a96953b0-07be-4145-4b42-fabc with PID 8 (/home/vcap/app/BOOT-INF/classes started by vcap in /home/vcap/app)
INFO 8 --- [           main] i.p.trustdemo.TrustDemoApplication       : The following profiles are active: cloud
INFO 8 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
INFO 8 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
INFO 8 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.29]
INFO 8 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
INFO 8 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3712 ms
INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
INFO 8 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
INFO 8 --- [           main] i.p.trustdemo.TrustDemoApplication       : Started TrustDemoApplication in 9.365 seconds (JVM running for 11.12)
INFO 8 --- [nio-8080-exec-3] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
INFO 8 --- [nio-8080-exec-3] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
INFO 8 --- [nio-8080-exec-3] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
INFO 8 --- [nio-8080-exec-3] ContainerTrustManagerFactory$PKIXFactory : Adding System Trust Manager
INFO 8 --- [nio-8080-exec-3] ContainerTrustManagerFactory$PKIXFactory : Adding TrustManager for /etc/ssl/certs/ca-certificates.crt
INFO 8 --- [tificates.crt-0] org.cloudfoundry.security.FileWatcher    : Start watching /etc/ssl/certs/ca-certificates.crt
INFO 8 --- [nio-8080-exec-3] c.s.FileWatchingX509ExtendedTrustManager : Initialized TrustManager for /etc/ssl/certs/ca-certificates.crt
INFO 8 --- [nio-8080-exec-3] oundryContainerKeyManagerFactory$SunX509 : Adding System Key Manager
INFO 8 --- [nio-8080-exec-3] oundryContainerKeyManagerFactory$SunX509 : Adding Key Manager for /etc/cf-instance-credentials/instance.key and /etc/cf-instance-credentials/instance.crt
INFO 8 --- [-instance.crt-0] org.cloudfoundry.security.FileWatcher    : Start watching /etc/cf-instance-credentials/instance.crt
INFO 8 --- [-instance.key-0] org.cloudfoundry.security.FileWatcher    : Start watching /etc/cf-instance-credentials/instance.key
INFO 8 --- [nio-8080-exec-3] o.c.s.FileWatchingX509ExtendedKeyManager : Initialized KeyManager for /etc/cf-instance-credentials/instance.key and /etc/cf-instance-credentials/instance.crt
...
```

**Comment by laura-burns** [comment]
Thanks Ben!  Big help!  What do I need to do in my microservice that I'm calling to ensure that there is a **mtls** between the two services?  

For example my microservice calls another microservice 
` @GetMapping("/getCaseList")
    @PreAuthorize("hasAnyAuthority('Employer.GetEmployer')")
    public ResponseEntity getCaseList(@RequestParam(required = false) String officerEmail) {
        HttpEntity<Object> requestEntity = new HttpEntity<>(null, authUtils.getNonRelayAuthHeaders());
        try{
        ResponseEntity response = restTemplate.exchange("https://casemangement/getCaseList?officerEmail=someofficer@gmail.com",
                HttpMethod.GET, requestEntity, Object.class);
        return new ResponseEntity(response.getBody(), authUtils.getResponseHeaders(response), response.getStatusCode());
        } catch (HttpClientErrorException e){
            return new ResponseEntity(e.getMessage(), e.getStatusCode());
        }
    }`

My receiving microservice call

 `@GetMapping("/getCaseList")
    public ResponseEntity getCaseList(@RequestParam(required = false) String officerEmail) {
        return new ResponseEntity(caseService.getCaseList(officerEmail), HttpStatus.OK);
    }`

**Comment by nebhale** [comment]
@laura-burns Not sure if this even still compiles, but you'll need to configure Spring Security to [use x509](https://github.com/nebhale/mtls-sample/blob/master/server/src/main/java/io/pivotal/mtlssample/server/ServerApplication.java#L96-L106).

**Comment by laura-burns** [comment]
What does the client side look like? I don't see it in the example...

**Comment by nebhale** [comment]
At this level I'm a bit fuzzy and it's really a question for the [Spring Security](https://stackoverflow.com/questions/tagged/spring-security) team.  My limited understanding though, is that if you need information that's been extracted from the certificate, using the `Principal` would be a good way to do it.
